### ISSUE TITLE
Final Checklist for Microsite from Client

### ISSUE THREAD

**Issue by ericholmer** [zebradog/taliesin-renewal-gala#4]
- [x] add a space after Odessa Piper's name (just above the head shots)
- [x] Edit sentence to read: Kyle Cherek of the Emmy Award-winning “Wisconsin Foodie” series will emcee.
- [x] under lodging, please add another option of a second night's stay. (I just heard back from the hotel that the same rate will apply.)
- [x] update the new field header so it reads "Names, Addresses & Emails of Additional Guest(s)"
- [x] Add Evening Attire
- [x] Add Sponsorship
